default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: get_tta_service_dev

test:
  <<: *default
  database: get_tta_service_test<%= ENV['TEST_ENV_NUMBER'] %>
  host: localhost
  username: postgres
  password: postgres

production: &production
  <<: *default
  uri: <%= Rails.application.config.x.vcap_services.dig("postgres", 0, "credentials", "uri") %>
